function logs = run_l2f_matlab_demo(varargin)
%RUN_L2F_MATLAB_DEMO Backward-compatible demo wrapper around l2f_rollout.

parser = inputParser;
addParameter(parser, 'horizon', 500);
addParameter(parser, 'batch_size', 1);
addParameter(parser, 'seed', 7);
addParameter(parser, 'live_plot', true);
addParameter(parser, 'controller', []);
addParameter(parser, 'environment', struct('type', 'none'));
addParameter(parser, 'dynamics_profile', 'fixed');
addParameter(parser, 'broad_sampler', 'legacy');
addParameter(parser, 'dt', 0.01);
addParameter(parser, 'mass', 0.05);
addParameter(parser, 'gravity', 9.80665);
addParameter(parser, 'arm_length', 0.046);
addParameter(parser, 'motor_tau', 0.06);
addParameter(parser, 'motor_authority', 1.35);
addParameter(parser, 'inertia_x', 1.4e-5);
addParameter(parser, 'inertia_y', 1.4e-5);
addParameter(parser, 'inertia_z', 2.17e-5);
parse(parser, varargin{:});
opt = parser.Results;

params = l2f_default_params( ...
    'dt', opt.dt, ...
    'mass', opt.mass, ...
    'gravity', opt.gravity, ...
    'arm_length', opt.arm_length, ...
    'motor_tau', opt.motor_tau, ...
    'motor_authority', opt.motor_authority, ...
    'inertia_x', opt.inertia_x, ...
    'inertia_y', opt.inertia_y, ...
    'inertia_z', opt.inertia_z, ...
    'dynamics_profile', opt.dynamics_profile, ...
    'broad_sampler', opt.broad_sampler);

world = l2f_make_world('empty', 'environment', opt.environment);
sensors = l2f_make_sensors('ideal');
reward_cfg = l2f_default_reward_cfg();
sim_cfg = l2f_default_sim_cfg( ...
    'horizon', opt.horizon, ...
    'batch_size', opt.batch_size, ...
    'seed', opt.seed, ...
    'live_plot', opt.live_plot);

logs = l2f_rollout(params, world, sensors, opt.controller, reward_cfg, sim_cfg);
end
